<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="assets/css/style.css" type="text/css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <title>Distortion</title>
</head>
<body>
    <header class="header">
        <div >
            <h1>Distortion</h1>
        </div>
        <nav class="nav">
            <ul>
                <a href="index.php?route=home"><li>Chat</li></a>
                 <a href="#"><li>A propos</li></a>
            </ul>
        </nav>
    </header>
    <main class="container">
        <?php require "templates/$route.phtml" ?> 
    </main>
    <script src="https://kit.fontawesome.com/3b11095cd8.js" crossorigin="anonymous"></script>
</body>
</html>