
<section class="form-salon">
    <h1>Salon</h1>
    <form action="index.php?route=check-salon" method="POST" class="form-salon">
        <fieldset>
            <label for="">Nom du Salon</label>
            <input type="text" name="name-salon" id="name-salon" required/>
        </fieldset>
        <input type="hidden" value="<?= (int)$_SESSION['selectedCategoryId'] ?>" name="categoriesId"/>
        <button type="submit" name="salon-submit" id="btn-form">Valider</button>
    </form>
</section>

